### ISSUE TITLE
pyModbus requirement version outdated

### ISSUE THREAD

**Issue by huub66** [ThaStealth/alfen_modbus#1]
First of all, thanks for creating this custom component. Great work!

I have an issue with the integration; pymodbus version requirement is 3.1.1 as from your code while homeassistant currently uses 3.5.2. When installing multiple integrations which use modbus, this integration stops working due to version conflict. 
Could you update the component, using the 3.5.2 version of pymodbus?

**Comment by ThaStealth** [comment]
Hi @huub66 ,

I created a new version which bumped the pymodbus component, I also fixed the mandatory changes. I'm not able to properly test it since I'm not near my HA server for the next few days.

**Comment by huub66** [comment]
Thanks for updating, sorry cannot validate this anymore as I've switched to the local API integration of the Alfen Wallbox.

**Comment by wouterpauwels** [comment]
Not working anymore after thé update....
